/**
 * scripts/deploy.js
 * -----------------
 * Deployment pipeline for the Blue Carbon MRV smart contract system.
 *
 * Steps:
 *   1. Deploy CarbonCreditToken ($BCO2)
 *   2. Deploy BlueCarbonRegistry (with token address)
 *   3. Set BlueCarbonRegistry as the authorised minter on CarbonCreditToken
 *   4. Export addresses + full ABIs to:
 *        blockchain/deployed_contracts.json  (for Hardhat / backend use)
 *        contracts_config.json               (workspace root, for FastAPI / Frontend)
 *
 * Usage:
 *   Local:        npx hardhat run scripts/deploy.js --network hardhat
 *   Polygon Amoy: npx hardhat run scripts/deploy.js --network amoy
 */

const { ethers, artifacts, network } = require("hardhat");
const fs   = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();

  console.log("=".repeat(60));
  console.log("  Blue Carbon MRV — Contract Deployment");
  console.log("=".repeat(60));
  console.log(`\nNetwork  : ${network.name}`);
  console.log(`Deployer : ${deployer.address}`);
  console.log(`Balance  : ${ethers.formatEther(await ethers.provider.getBalance(deployer.address))} ETH\n`);

  // ── 1. Deploy CarbonCreditToken ────────────────────────────────────────────
  console.log("Deploying CarbonCreditToken ($BCO2)...");
  const TokenFactory = await ethers.getContractFactory("CarbonCreditToken");
  const token = await TokenFactory.deploy(deployer.address);
  await token.waitForDeployment();
  const tokenAddress = await token.getAddress();
  console.log(`  [OK] CarbonCreditToken deployed -> ${tokenAddress}`);

  // ── 2. Deploy BlueCarbonRegistry ──────────────────────────────────────────
  console.log("\nDeploying BlueCarbonRegistry...");
  const RegistryFactory = await ethers.getContractFactory("BlueCarbonRegistry");
  const registry = await RegistryFactory.deploy(tokenAddress, deployer.address);
  await registry.waitForDeployment();
  const registryAddress = await registry.getAddress();
  console.log(`  [OK] BlueCarbonRegistry deployed -> ${registryAddress}`);

  // ── 3. Authorise registry as minter on the token ──────────────────────────
  console.log("\nSetting BlueCarbonRegistry as minter on CarbonCreditToken...");
  const tx = await token.setMinter(registryAddress);
  await tx.wait();
  console.log(`  [OK] Minter set. Tx: ${tx.hash}`);

  // ── 4. Verify minter was set correctly ────────────────────────────────────
  const minterOnChain = await token.minter();
  console.log(`  [OK] Confirmed minter on-chain: ${minterOnChain}`);
  if (minterOnChain.toLowerCase() !== registryAddress.toLowerCase()) {
    throw new Error("Minter mismatch — deployment aborted.");
  }

  // ── 5. Load ABIs from compiled artifacts ──────────────────────────────────
  const tokenArtifact    = await artifacts.readArtifact("CarbonCreditToken");
  const registryArtifact = await artifacts.readArtifact("BlueCarbonRegistry");

  // ── 6. Build deployment output ────────────────────────────────────────────
  const deploymentData = {
    _comment    : "Auto-generated by scripts/deploy.js — do not edit manually.",
    network     : network.name,
    chainId     : network.config.chainId ?? 31337,
    deployedAt  : new Date().toISOString(),
    deployer    : deployer.address,
    contracts: {
      CarbonCreditToken: {
        address : tokenAddress,
        symbol  : "BCO2",
        decimals: 18,
        abi     : tokenArtifact.abi,
      },
      BlueCarbonRegistry: {
        address : registryAddress,
        abi     : registryArtifact.abi,
      },
    },
  };

  // ── 7. Read existing or create new multi-network structures ────────────────
  const blockchainOut = path.join(__dirname, "..", "deployed_contracts.json");
  let allDeployments = {};
  if (fs.existsSync(blockchainOut)) {
    try {
      allDeployments = JSON.parse(fs.readFileSync(blockchainOut, "utf8"));
    } catch (e) {
      console.warn("Could not parse existing deployed_contracts.json, starting fresh.");
    }
  }

  const rootOut = path.join(__dirname, "..", "..", "contracts_config.json");
  let rootConfigAll = {};
  if (fs.existsSync(rootOut)) {
    try {
      rootConfigAll = JSON.parse(fs.readFileSync(rootOut, "utf8"));
    } catch (e) {
      console.warn("Could not parse existing contracts_config.json, starting fresh.");
    }
  }

  // ── 8. Update structures for current network ────────────────────────────────
  allDeployments[network.name] = deploymentData;
  fs.writeFileSync(blockchainOut, JSON.stringify(allDeployments, null, 2));
  console.log(`\n[OK] blockchain/deployed_contracts.json updated for network '${network.name}'`);

  const rootConfig = {
    _comment  : "Auto-generated by blockchain/scripts/deploy.js",
    network   : deploymentData.network,
    chainId   : deploymentData.chainId,
    deployedAt: deploymentData.deployedAt,
    contracts : {
      CarbonCreditToken: {
        address : tokenAddress,
        symbol  : "BCO2",
        decimals: 18,
      },
      BlueCarbonRegistry: {
        address: registryAddress,
      },
    },
  };
  rootConfigAll[network.name] = rootConfig;
  fs.writeFileSync(rootOut, JSON.stringify(rootConfigAll, null, 2));
  console.log(`[OK] contracts_config.json updated to workspace root for network '${network.name}'`);

  // ── 9. Summary ────────────────────────────────────────────────────────────
  console.log("\n" + "=".repeat(60));
  console.log("  Deployment Summary");
  console.log("=".repeat(60));
  console.log(`  CarbonCreditToken  : ${tokenAddress}`);
  console.log(`  BlueCarbonRegistry : ${registryAddress}`);
  console.log(`  Minter set to      : ${minterOnChain}`);
  console.log(`  Network            : ${network.name}`);
  console.log("=".repeat(60));
  console.log("\nDeployment complete.\n");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
